package com.example.readtrace.model

import android.graphics.Color

enum class WidgetCardTheme(
    val displayName: String,
    val description: String,
    val bgColor: Int,
    val cardBgColor: Int,
    val strokeColor: Int,
    val textPrimaryColor: Int,
    val textMutedColor: Int,
    val accentColor: Int,
    val pillBgColor: Int,
    val radarFillColor: Int,
    val radarStrokeColor: Int,
    val radarDotColor: Int,
    val radarWebColor: Int,
    val radarAxisColor: Int,
) {
    ALABASTER_PAPER(
        displayName = "📜 极简白晶纸",
        description = "温暖宣纸底色 · 墨绿点睛 · 苹果极简呼吸感",
        bgColor = Color.parseColor("#F5F3EC"),
        cardBgColor = Color.parseColor("#FFFFFF"),
        strokeColor = Color.parseColor("#26000000"),
        textPrimaryColor = Color.parseColor("#1C201C"),
        textMutedColor = Color.parseColor("#7A8075"),
        accentColor = Color.parseColor("#3A6348"),
        pillBgColor = Color.parseColor("#EDF3EE"),
        radarFillColor = Color.parseColor("#553A6348"),
        radarStrokeColor = Color.parseColor("#3A6348"),
        radarDotColor = Color.parseColor("#264530"),
        radarWebColor = Color.parseColor("#DDD4CA"),
        radarAxisColor = Color.parseColor("#EADFD5"),
    ),
    OBSIDIAN_GOLD(
        displayName = "👑 深邃黑曜金",
        description = "纯粹黑曜石 · 流光琥珀金 · 高贵典藏质感",
        bgColor = Color.parseColor("#0E110F"),
        cardBgColor = Color.parseColor("#181C19"),
        strokeColor = Color.parseColor("#33E0A96D"),
        textPrimaryColor = Color.parseColor("#F5F1E9"),
        textMutedColor = Color.parseColor("#A89E8E"),
        accentColor = Color.parseColor("#E0A96D"),
        pillBgColor = Color.parseColor("#2A241B"),
        radarFillColor = Color.parseColor("#55E0A96D"),
        radarStrokeColor = Color.parseColor("#E0A96D"),
        radarDotColor = Color.parseColor("#FFC88A"),
        radarWebColor = Color.parseColor("#383228"),
        radarAxisColor = Color.parseColor("#2C261D"),
    ),
    CYBER_EMERALD(
        displayName = "🧪 赛博荧光绿",
        description = "深邃夜蓝 · 极光荧光绿 · 前沿科幻全息感",
        bgColor = Color.parseColor("#0B1210"),
        cardBgColor = Color.parseColor("#111D19"),
        strokeColor = Color.parseColor("#4400FF9D"),
        textPrimaryColor = Color.parseColor("#ECFDF5"),
        textMutedColor = Color.parseColor("#6EE7B7"),
        accentColor = Color.parseColor("#00FF9D"),
        pillBgColor = Color.parseColor("#142E25"),
        radarFillColor = Color.parseColor("#5500FF9D"),
        radarStrokeColor = Color.parseColor("#00FF9D"),
        radarDotColor = Color.parseColor("#A7F3D0"),
        radarWebColor = Color.parseColor("#1B382F"),
        radarAxisColor = Color.parseColor("#132922"),
    ),
    SUNSET_CORAL(
        displayName = "🌇 晚霞落日橙",
        description = "暮色微紫 · 落日珊瑚暖橙 · 浪漫微醺情感",
        bgColor = Color.parseColor("#1A141A"),
        cardBgColor = Color.parseColor("#261B24"),
        strokeColor = Color.parseColor("#44FF7A59"),
        textPrimaryColor = Color.parseColor("#FFF1F2"),
        textMutedColor = Color.parseColor("#FDA4AF"),
        accentColor = Color.parseColor("#FF7A59"),
        pillBgColor = Color.parseColor("#381F2C"),
        radarFillColor = Color.parseColor("#55FF7A59"),
        radarStrokeColor = Color.parseColor("#FF7A59"),
        radarDotColor = Color.parseColor("#FFA07A"),
        radarWebColor = Color.parseColor("#422838"),
        radarAxisColor = Color.parseColor("#311D2A"),
    ),
}
